language: node_js
node_js:
- '0.10'
env:
  global:
    - secure: TMa4UwFKDP9nyiLc/uXPrLQlRNokVsAwqh7Q2+cwkbe+Dpxj8TbZuhYlGFzrBU3zOVvdu/Yv5fG6dlo1xA4WrDr4G8ZS2sInXq/colJ2lRnSjOfN5tF0lcN4mqFgA9++qQ8+/GtpP0XzPrEYcbm/Pmg9eCwlaHkM/rASFFaDlPQ=
    - secure: kwgJkf0MCY6Z2g963RYM3lMSGr2YiLAZRHeUzrwy9haVvRlQveZ5d3TGKk8Oq/Lo0l5V7YFU//PRi378j0pLWGBHmqWN3/dvJHWNNbOCrcOztK4Wa/OBjOW7EUWpRX6syrj4cCq9ut2DDeXCI72cgQTzYrLDH6vmo59edM+Ly3U=
notifications:
  email: false
before_script: npm install -g karma-cli
